# .github/workflows/release.yml
name: release
on:
  push:
    tags: ['v*.*.*']        # 태그만 트리거
jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install build
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}

  docs:
    needs: build-upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install mkdocs-material mkdocstrings[python]
      - run: mkdocs gh-deploy --clean --force