on:
  push:
    tags: ["*.*.*"]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - run: pip install build
      - run: python -m build  # wheel+sdist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}